name: TAnzeb
description: "Diocese of Shebin al-Qanater and its environs"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #  sqflite: ^2.2.4+1
  #  google_nav_bar: ^5.0.6
  shared_preferences: ^2.2.0
  awesome_notifications: any
  image_picker: ^1.0.1
  geolocator: ^9.0.2
  #  translator: ^0.1.7
  dartz: ^0.10.1
  equatable: ^2.0.5
  fluttertoast: ^8.1.3
  flutter_bloc: ^8.1.2
  #  animate_do: ^3.0.2
  url_launcher: ^6.1.9
  get_it: ^7.2.0
  shimmer: ^3.0.0
  intl: any
  cached_network_image: ^3.2.3
  modal_bottom_sheet: ^2.1.2
  background_fetch: ^1.1.4
  iconly: ^1.0.1
  #  easy_stepper: ^0.7.3
  #  photo_view: ^0.14.0
  #  readmore: ^2.2.0
  #  telephony: ^0.2.0
  record: ^4.4.4
  font_awesome_flutter: ^10.4.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.13
  #  animations: ^2.0.7
  #  multi_select_flutter: ^4.1.3
  #  carousel_slider: ^4.2.1
  google_fonts: ^4.0.3
  flutter_awesome_select: ^6.5.0
  animated_text_kit: ^4.2.2
  image_cropper: ^4.0.1
  dotted_border: ^2.0.0+3
  #  flutter_rating_bar: ^4.0.1
  #  flutter_image_compress: ^2.0.3
  audioplayers: ^5.0.0
  smooth_page_indicator: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  speech_to_text: ^6.1.1
  flutter_svg: ^2.0.7
  audio_waveforms: ^1.0.4
  file_picker: ^5.3.3
  dio: ^5.4.0
#  internet_connection_checker: ^1.0.0+1
#  connectivity_plus: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: ^2.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
